CREATE DATABASE IF NOT EXISTS event_management;
USE event_management;

CREATE TABLE Users (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE Events (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(200) NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Date DATETIME NOT NULL,
    OrganizerId INT,
    FOREIGN KEY (OrganizerId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE RSVPs (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    UserId INT,
    EventId INT,
    IsAttending BOOLEAN NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (EventId) REFERENCES Events(Id) ON DELETE CASCADE
);
